build:
  image: node:6
  commands:
    - "npm install"
    - "npm install buildgoggles@0.2.0-3"
    - "./node_modules/buildgoggles/bin/buildgoggles --releaseOwner=jgreat --releaseBranch=master"

cache:
  mount:
    - node_modules
    - .git

publish:
  # Publish to DockerHub
  docker:
    image: jgreat/drone-docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: jgreat/vote-demo-worker
    storage_driver: zfs

deploy:
  # Deploy to Rancher Enviornment via Cowpoke Service
  cowpoke:
    image: leankit/drone-cowpoke:logging
    docker_username: $$DOCKER_USER
    docker_password: $$DOCKER_PASS
    docker_repo: jgreat/vote-demo-worker
    catalog_repo: jgreat/rancher-vote-demo-worker
    github_token: $$GITHUB_TOKEN
    github_user: $$GITHUB_USER
    github_email: $$GITHUB_EMAIL
    cowpoke_url: https://cowpoke.leankitdev.com:9300
    rancher_catalog_name: vote-demo-worker
    bearer_token: $$COWPOKE_API_KEY
