# Default values for vote-demo-worker.
domainName: eng.rancher.space

image:
  repository: jgreat/vote-demo-worker
  # tag: latest
  pullPolicy: IfNotPresent

ingress:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: []

replicaCount: 1

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
